version: '3.9'

services:
  mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      ports:
       - 2717:27017
      volumes: 
        - mongo_db:/data/db
  
  api:
    build: .
    container_name: chat-app-backend
    restart: always
    ports:
      - "5777:8080"
    env_file:
      - ./.env
    depends_on:
     - mongo_db
    volumes:
      - .:/app

volumes:
   mongo_db: {}
