version: '3.8'

services:
  app:
    build: .
    container_name: chat-app-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env

    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:4.4
    container_name: chat-app-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local
